config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :pins do
    member do
      put "like", to: "pins#upvote"
    end
  end

  root "pins#index"

end

app/models/pin.rb
class Pin < ActiveRecord::Base
	acts_as_votable
	belongs_to :user

	has_attached_file :image, styles: {medium: "300x300>"} 
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
	before_action :find_pin, only: [:show, :edit, :update, :destroy, :upvote]
	before_action :authenticate_user!, except: [:index, :show]

	def index
		@pins = Pin.all.order("created_at DESC")
	end

	def show
	end

	def new
		@pin = current_user.pins.build
	end

	def create
		@pin = current_user.pins.build(pin_params)

		if @pin.save
			redirect_to @pin
		else
			render 'new'
		end

	end

	def edit
	end

	def update
		if @pin.update(pin_params)
			redirect_to @pin
		else
			render 'edit'
		end
	end

	def destroy
		@pin.destroy
		redirect_to root_path
	end

	def upvote
		@pin.upvote_by current_user
		redirect_to :back
	end

	private

	def pin_params
		params.require(:pin).permit(:title, :description, :image)
	end

	def find_pin
		@pin = Pin.find(params[:id])
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pinterfai</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body style="padding-top: 4em;">
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">
        <img alt="Brand" src="...">
      </a>
      <p class="navbar-text navbar-right">
      <% if user_signed_in? %>
        Logged in as <strong><%= current_user.email %></strong>
        <%= link_to 'Profile', edit_user_registration_path, :class => 'navbar-link' %> |
        <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
      <% else %>
        <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
        <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %><br>
      <% end %></p>
    </div>
  </div>
</nav>

<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<div class="container-fluid">
<%= yield %>
</div>

</body>
</html>

app/views/pins/_form.html.erb
<%= simple_form_for @pin do |f|%>
	<% if @pin.errors.any? %>
		<div id="error_explanation">
			<h2>
				<%= pluralize(@pin.errors.count, "error") %>
				prevented pin from saving
			</h2>
			<ul>
				<% @pin.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<p>
		<%= f.label :image %><br>
		<%= f.input_field :image, class: "form_control" %>
	</p>
	<p>
		<%= f.label :title %><br>
		<%= f.input_field :title, class: "form_control" %>
	</p>
	<p>
		<%= f.label :description %><br>
		<%= f.input_field :description, class: "form_control" %>
	</p>
	<p>
		<%= f.button :submit %>
	</p>

<% end %>

app/views/pins/edit.html.erb
<div class="col-md-6 col-md-offset-3">
<h1>Edit Pin</h1>
<%= image_tag(@pin.image.url(:medium)) %>
<%= render 'pins/form' %>

<%= link_to 'Cancel', @pin %>
</div>

app/views/pins/index.html.erb
<h1>Index for Pins</h1>
<h2><%= link_to "New Pin", new_pin_path %></h2>

<div id="pins" class="transitions-enabled">
<% @pins.each do |pin| %>
	<div class="box panel panel-default">
		<%= link_to image_tag(pin.image.url), pin %>
			<div class="panel-body">
				<h2><%= link_to pin.title, pin %></h2>
			</div>
	</div>
<% end %>
</div>

app/views/pins/new.html.erb
<div class="col-md-6 col-md-offset-3">
	<div class="row">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h1>New Pin</h1>
			</div>
			<div class="panel-body">
				<%= render 'pins/form' %>
			</div>
			<div class="panel-footer">
				<%= link_to 'Back', root_path %>
			</div>
		</div>
	</div>
</div>

app/views/pins/show.html.erb
<div id="pin_show" class="row">
	<div class="col-md-8 col-md-offset-2"> 
		<div class="panel panel-default">
			<div class="panel-heading pin_image">
				<%= image_tag(@pin.image.url) %>
			</div>
			<div class="panel-body">
				<h1><%= @pin.title %></h1>
				<p class="description"><%= @pin.description %></p>
				<p>Submitted by <%= @pin.user.email %></p>
			</div>
			<div class="panel-footer">
				<div class="row">
					<div class="col-md-6">
						<div class="btn-group.pull-right">
							<%= @pin.get_upvotes.size %>
							<%= link_to 'Like', like_pin_path(@pin), method: :put, class: "btn btn-default"%>
							<%= link_to 'Back', root_path, class: "btn btn-default" %>
							<% if user_signed_in? %>
								<%= link_to 'Edit', edit_pin_path, class: "btn btn-default" %>
								<%= link_to 'Delete', pin_path, method: :delete, data: {
								confirm: "delete this pin?" }, class: "btn btn-default" %>
							<%end%>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>